apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gamefeed-frontend.resourceName" . }}
  namespace: {{ include "gamefeed-frontend.namespace" . }}
  labels:
    app: {{ include "gamefeed-frontend.resourceName" . }}
    {{- include "gamefeed-frontend.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "gamefeed-frontend.resourceName" . }}
  template:
    metadata:
      labels:
        app: {{ include "gamefeed-frontend.resourceName" . }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{ end }}
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{ end }}
    spec:
      containers:
        - name: {{ include "gamefeed-frontend.resourceName" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.containerPort }}
          volumeMounts:
            - name: frontend-nginx-conf
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
          readinessProbe:
            tcpSocket:
              port: {{ .Values.containerPort }}
            initialDelaySeconds: {{ .Values.probes.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.readiness.periodSeconds }}
            failureThreshold: {{ .Values.probes.readiness.failureThreshold }}
          livenessProbe:
            tcpSocket:
              port: {{ .Values.containerPort }}
            initialDelaySeconds: {{ .Values.probes.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.liveness.periodSeconds }}
            failureThreshold: {{ .Values.probes.liveness.failureThreshold }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: frontend-nginx-conf
          configMap:
            name: {{ .Values.nginx.configMapName }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{ end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{ end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{ end }}
