{{- if .Values.namespace.create }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "gamefeed-user-service.namespace" . }}
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- end }}
