apiVersion: v1
kind: Service
metadata:
  name: {{ include "gamefeed-database.resourceName" . }}
  namespace: {{ include "gamefeed-database.namespace" . }}
  labels:
    app: {{ include "gamefeed-database.resourceName" . }}
    {{- include "gamefeed-database.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app: {{ include "gamefeed-database.resourceName" . }}
  ports:
    - name: postgres
      port: {{ .Values.postgres.port }}
      targetPort: {{ .Values.postgres.port }}
