apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "gamefeed-config.resourceName" . }}
  namespace: {{ include "gamefeed-config.namespace" . }}
  labels:
    {{- include "gamefeed-config.labels" . | nindent 4 }}
data:
  {{ range $key, $value := .Values.config.data }}
  {{ $key }}: {{ $value | quote }}
  {{ end }}
