{{- if .Values.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  namespace: {{ include "gamefeed-database.namespace" . }}
  labels:
    {{- include "gamefeed-database.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ range $key, $value := .Values.secret.stringData }}
  {{ $key }}: {{ $value | quote }}
  {{ end }}
{{- end }}
