global:
  namespace: ""

namespace:
  create: false
  name: gamefeed

resourceName: comment-service
replicaCount: 1

image:
  repository: dheerajkadve/gamefeed-comment-service
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 8084

containerPort: 8084

secret:
  name: gamefeed-secret
  usernameKey: POSTGRES_USER
  passwordKey: POSTGRES_PASSWORD

jwt:
  enabled: false
  secretKey: JWT_SECRET

database:
  host: postgres-db
  port: 5432
  name: comment_db

waitForDatabase:
  enabled: true
  image: busybox:1.36
  sleepSeconds: 3

podLabels: {}
podAnnotations: {}

probes:
  readiness:
    initialDelaySeconds: 20
    periodSeconds: 10
    failureThreshold: 12
  liveness:
    initialDelaySeconds: 60
    periodSeconds: 20
    failureThreshold: 6

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 700m
    memory: 768Mi

nodeSelector: {}
tolerations: []
affinity: {}
